name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build with Gradle
        run: ./gradlew clean build -x test

      - name: Get built JAR name
        id: get-jar
        run: |
          JAR_NAME=$(ls build/libs/*.jar | head -n 1)
          echo "JAR_NAME=${JAR_NAME}" >> $GITHUB_ENV

      - name: Check if JAR file exists
        run: ls -al build/libs

      - name: Copy JAR file to EC2
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_KEY }}
          source: "${{ env.JAR_NAME }}"
          target: "~/app/Chingu-Backend-0.0.1-SNAPSHOT.jar"
          overwrite: true

      - name: Copy start.sh script to EC2
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_KEY }}
          source: "start.sh"
          target: "~/app"
          overwrite: true

      - name: Run start.sh on EC2
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_KEY }}
          script: |
            cd ~/app
            chmod +x start.sh
            nohup ./start.sh > app.log 2>&1 &
