name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build with Gradle
        run: ./gradlew clean build -x test

      - name: Check if JAR file exists
        run: |
          ls -al build/libs
      - name: Deploy to EC2
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_KEY }}
          source: "build/libs/Chingu-Backend-0.0.1-SNAPSHOT.jar"
          target: "~/"

      - name: Run app on EC2
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_KEY }}
          script: |
            java -version
            pkill -f 'java -jar' || true
            ls -al ~
            nohup java -jar ~/Chingu-Backend-0.0.1-SNAPSHOT.jar > ~/app.log 2>&1 &
            sleep 5
            ps -ef | grep java
